# Generated by Django 4.0.6 on 2023-04-20 19:49

from django.db import migrations
import enumchoicefield.fields
import yummy.models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=enumchoicefield.fields.EnumChoiceField(blank=True, enum_class=yummy.models.CuisineType, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='department',
            field=enumchoicefield.fields.EnumChoiceField(default=yummy.models.DepartmentType(2), enum_class=yummy.models.DepartmentType, max_length=11),
        ),
    ]
