# Generated by Django 4.0.6 on 2023-03-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='URL'),
        ),
    ]
