# Generated by Django 4.0.6 on 2023-02-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='yummy.ingredient', verbose_name='Ингредиент'),
        ),
    ]
