# Generated by Django 4.2.2 on 2023-06-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0002_alter_recipe_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(choices=[('russia', 'Русская кухня'), ('france', 'Французская кухня'), ('georgia', 'Грузинская кухня'), ('italia', 'Итальянская кухня'), ('japan', 'Японская кухня'), ('india', 'Индийская кухня'), ('china', 'Китайская кухня'), ('asia', 'Азиатская кухня'), ('mexico', 'Мексиканская кухня'), ('europe', 'Европейская кухня'), ('caucasus', 'Кавказская кухня'), ('uzbekistan', 'Узбекская кухня'), ('turkey', 'Турецкая кухня'), ('america', 'Американская кухня'), ('spain', 'Испанская кухня'), ('greece', 'Греческая кухня')], default='russia', verbose_name='Кухня'),
        ),
    ]
