# Generated by Django 4.0.6 on 2023-04-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0002_alter_recipe_cuisine_alter_recipe_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='empty.png', upload_to='', verbose_name='Фотография'),
        ),
    ]
