# Generated by Django 4.0.6 on 2023-05-13 17:15

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import yummy.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_photo'),
        ('yummy', '0002_alter_goods_options_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.profile', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_recipes', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=enumchoicefield.fields.EnumChoiceField(blank=True, enum_class=yummy.models.CuisineType, max_length=10, verbose_name='Кухня'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='department',
            field=enumchoicefield.fields.EnumChoiceField(default=yummy.models.DepartmentType(2), enum_class=yummy.models.DepartmentType, max_length=11, verbose_name='Тип блюда'),
        ),
    ]
