# Generated by Django 4.0.6 on 2023-04-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.FileField(upload_to='recipes', verbose_name='Фотография'),
        ),
    ]
