# Generated by Django 4.0.6 on 2023-02-20 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0003_alter_recipe_author_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='cuisine_name',
            field=models.CharField(blank=True, choices=[('ru', 'русская кухня'), ('fr', 'французская кухня'), ('gr', 'грузинская кухня'), ('it', 'итальянская кухня'), ('jp', 'японская кухня'), ('ind', 'индийская кухня'), ('chn', 'китайская кухня'), ('as', 'азиатская кухня'), ('mx', 'мексиканская кухня'), ('eur', 'европейская кухня'), ('kvz', 'кавказская кухня'), ('uz', 'узбекская кухня'), ('tr', 'турецкая кухня'), ('amr', 'американская кухня'), ('sp', 'испанская кухня'), ('ukr', 'украинская кухня'), ('grec', 'греческая кухня'), ('o', 'другие кухни')], max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('b', 'выпечка'), ('d', 'дессерты'), ('m', 'вторые блюда'), ('s', 'закуски'), ('sal', 'салаты'), ('sp', 'первые блюда'), ('dr', 'напитки'), ('ss', 'соусы'), ('can', 'заготовки на зиму')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient',
            field=models.CharField(choices=[('мясо и птица', (('chicken', 'курица'), ('beef', 'говядина'), ('pork', 'свинина'))), ('рыба', (('salmon', 'лосось'), ('с_tuna', 'тунец консервированный'), ('mackerel', 'скумбрия'), ('pollock', 'минтай'), ('cod', 'треска'))), ('овощи', (('potato', 'картофель'), ('carrot', 'моковь'), ('onion', 'лук'), ('corn', 'кукуруза'), ('mushrooms', 'грибы'), ('lettuce', 'салат'), ('c_corn', 'консервированная кукуруза'), ('champignons', 'шампиньоны'), ('arugula', 'руккола'), ('cabbage', 'капуста'), ('cauliflower', 'цветная капуста'), ('broccoli', 'брокколи'), ('beet', 'свекла'), ('garlic', 'чеснок'), ('basil', 'базилик'), ('tomatoes', 'помидор'), ('cucumber', 'огурец'), ('paprika', 'сладкий перец'), ('hot_pepper', 'острый перец'), ('zucchini', 'кабачок'), ('eggplant', 'баклажан'), ('pumpkin', 'тыква'), ('b_olives', 'маслины'), ('olives', 'оливки'), ('string beans', 'стручковая фасоль'), ('parsley', 'петрушка'), ('cilantro', 'кинза'), ('dill', 'укроп'))), ('яйца', (('egg', 'яйцо'), ('yolk', 'желток'), ('protein', 'белок'))), ('фрукты', (('apple', ''), ('orange', ''), ('banana', ''), ('strawberry', 'клубника'), ('peach', 'персик'), ('pear', 'груша'), ('grape', 'виноград'))), ('крупы', (('buckwheat', 'гречка'), ('haricot', 'фасоль'), ('lentils', 'чечевица'), ('rice', 'рис'), ('couscous', 'кускус'), ('bulgur', 'булгур'), ('pasta', 'макароны'), ('spaghetti', 'спагетти'))), ('специи', (('bl_pepper', 'черный перец'), ('cinnamon', 'корица'), ('coriander', 'кориандр'), ('mustard', 'горчица'), ('ginger', 'имбирь'), ('red wine', 'красное вино'), ('white wine', 'белое вино'), ('beer', 'пиво'))), ('соусы', (('mustard', 'горчица'), ('ketchup', 'кетчуп'), ('tomato paste', 'томатная паста'), ('mayonnaise', 'майонез'), ('balsamic', 'бальзамический соус'), ('vinegar', 'уксус'), ('lemon juice', 'лимонный сок'), ('sugar', 'сахар'), ('salt', 'соль'))), ('молочные продукты', (('milk', 'молоко'), ('sour cream', 'сметана'), ('cream', 'сливки'), ('kefir', 'кефир'), ('yogurt', 'йогурт'), ('curd', 'творог'), ('cheese', 'сыр'), ('parmesan', 'пармезан'), ('mozzarella', 'моцарелла'))), ('выпечка', (('flour', 'мука'), ('yeasts', 'дрожжи'), ('soda', 'сода'), ('baking powder', 'разрыхлитель'))), ('напитки', (('cocoa', 'какао'), ('coffee', 'кофе'), ('water', 'вода'), ('tea', 'чай'), ('apple juice', 'яблочный сок'), ('orange juice', 'апельсиновый сок'))), ('сухофрукты', (('raisin', 'изюм'), ('prunes', 'чернослив'), ('walnuts', 'грецкие орехи'), ('almond', 'миндаль'), ('peanut', 'арахис'), ('dried apricots', 'курага')))], max_length=40),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.PositiveIntegerField(choices=[('kg', 'кг'), ('gr', 'гр'), ('l', 'л'), ('ml', 'мл'), ('tea_s', 'ч. л.'), ('tbl_s', 'ст. л.'), ('tst', 'по вкусу')], verbose_name='Колличество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yummy.cuisine'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_in_minutes',
            field=models.PositiveIntegerField(choices=[('min', ' мин'), ('hr', 'ч')], verbose_name='Время приготовления'),
        ),
    ]
