# Generated by Django 4.0.6 on 2023-02-24 12:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0004_alter_cuisine_cuisine_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('type', models.CharField(choices=[('M', 'мясо и птица'), ('F', 'рыба'), ('V', 'овощи'), ('EG', 'яйца'), ('FR', 'фрукты'), ('P', 'крупы'), ('SP', 'специи'), ('SS', 'соусы'), ('ML', 'молочные продукты'), ('B', 'выпечка'), ('D', 'напитки'), ('N', 'сухофрукты')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity_type',
            field=models.CharField(choices=[('KG', 'кг.'), ('GR', 'гр.'), ('L', 'л.'), ('ML', 'мл.'), ('TEA_S', 'ч. л.'), ('TBL_S', 'ст. л.'), ('PC', 'шт.'), ('TST', 'по вкусу')], default='гр.', max_length=10, verbose_name='Колличество'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(blank=True, choices=[('RU', 'русская кухня'), ('FR', 'французская кухня'), ('GR', 'грузинская кухня'), ('IT', 'итальянская кухня'), ('JP', 'японская кухня'), ('IND', 'индийская кухня'), ('CHN', 'китайская кухня'), ('AS', 'азиатская кухня'), ('MX', 'мексиканская кухня'), ('EUR', 'европейская кухня'), ('KVZ', 'кавказская кухня'), ('UZ', 'узбекская кухня'), ('TR', 'турецкая кухня'), ('AMR', 'американская кухня'), ('SP', 'испанская кухня'), ('GRC', 'греческая кухня')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='department',
            field=models.CharField(choices=[('B', 'выпечка'), ('D', 'дессерты'), ('M', 'вторые блюда'), ('S', 'закуски'), ('SL', 'салаты'), ('SP', 'первые блюда'), ('DR', 'напитки'), ('SS', 'соусы'), ('CAN', 'заготовки на зиму')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yummy.goods'),
        ),
    ]
