# Generated by Django 4.0.6 on 2023-03-04 18:15

import django.core.validators
from django.db import migrations, models
import enumchoicefield.fields
import yummy.models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0005_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['type'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['ingredient'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['date', 'name'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='time_in_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Время приготовления(ч.)'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(error_messages={'unique': 'Продукт с таким названием уже существует'}, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='type',
            field=enumchoicefield.fields.EnumChoiceField(default=yummy.models.GoodsType(3), enum_class=yummy.models.GoodsType, max_length=2, verbose_name='Тип продукта'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_in_minutes',
            field=models.PositiveIntegerField(verbose_name='Время приготовления(мин.)'),
        ),
    ]
