# Generated by Django 4.0.6 on 2023-03-07 14:09

from django.db import migrations, models
import enumchoicefield.fields
import yummy.models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0006_alter_goods_options_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_type',
            field=enumchoicefield.fields.EnumChoiceField(default=yummy.models.ProductQuantity(2), enum_class=yummy.models.ProductQuantity, max_length=5, verbose_name='Единицы измерения'),
        ),
    ]
