# Generated by Django 4.0.6 on 2023-05-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0006_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, default='', through='yummy.Ingredient', to='yummy.goods', verbose_name='Ингредиент'),
        ),
    ]
