# Generated by Django 4.0.6 on 2023-02-25 15:29

from django.db import migrations
import enumchoicefield.fields
import yummy.models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0006_alter_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='type',
            field=enumchoicefield.fields.EnumChoiceField(default=yummy.models.GoodsType(3), enum_class=yummy.models.GoodsType, max_length=2),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_type',
            field=enumchoicefield.fields.EnumChoiceField(default=yummy.models.ProductQuantity(2), enum_class=yummy.models.ProductQuantity, max_length=5, verbose_name='Колличество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=enumchoicefield.fields.EnumChoiceField(blank=True, default=yummy.models.CuisineType(10), enum_class=yummy.models.CuisineType, max_length=3),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='department',
            field=enumchoicefield.fields.EnumChoiceField(default=yummy.models.DepartmentType(3), enum_class=yummy.models.DepartmentType, max_length=3),
        ),
    ]
