# Generated by Django 4.0.6 on 2023-05-24 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0006_alter_comments_options_alter_goods_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yummy.recipe', verbose_name='Рецепт'),
        ),
    ]
