# Generated by Django 4.0.6 on 2023-05-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0007_alter_ingredient_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ('name',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
