# Generated by Django 4.0.6 on 2023-03-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0007_alter_ingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='yummy.Ingredient', to='yummy.goods', verbose_name='Ингредиент'),
        ),
    ]
