# Generated by Django 4.0.6 on 2023-05-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0008_alter_goods_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('ingredient__name',), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
    ]
