# Generated by Django 4.0.6 on 2023-05-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0009_alter_ingredient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-date',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
