# Generated by Django 4.0.6 on 2023-05-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0010_alter_comments_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-date', 'name'), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
