# Generated by Django 4.0.6 on 2023-05-25 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0012_alter_ingredient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5000), django.core.validators.MinValueValidator(0.1)], verbose_name='Количество'),
        ),
    ]
