# Generated by Django 4.0.6 on 2023-05-25 15:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_options'),
        ('yummy', '0013_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(error_messages={'max_length': 'Название продукта слишком длинное', 'min_length': 'Название продукта слишком короткое', 'unique': 'Продукт с таким названием уже существует'}, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5000), django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.profile', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(error_messages={'max_length': 'Описание рецепта слишком длинное', 'min_length': 'Описание рецепта слишком короткое'}, max_length=3000, verbose_name='Приготовление'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(error_messages={'max_length': 'Название рецепта слишком длинное', 'min_length': 'Название рецепта слишком короткое'}, max_length=100, verbose_name='Название'),
        ),
    ]
