# Generated by Django 4.0.6 on 2023-05-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0014_alter_goods_name_alter_ingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, null=True),
        ),
    ]
