# Generated by Django 4.0.6 on 2023-05-26 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0015_alter_comments_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Комментарий слишком короткий'), django.core.validators.MaxLengthValidator(limit_value=500, message='Комментарий слишком длинный')], verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Название продукта слишком короткое'), django.core.validators.MaxLengthValidator(limit_value=50, message='Название продукта слишком длинное')], verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=1000, message='Количество слишком большое'), django.core.validators.MinValueValidator(limit_value=0.001, message='Количество слишком маленькое')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(max_length=3000, validators=[django.core.validators.MinLengthValidator(limit_value=40, message='Описание рецепта слишком короткое'), django.core.validators.MaxLengthValidator(limit_value=3000, message='Описание рецепта слишком длинное')], verbose_name='Приготовление'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='yummy.Ingredient', to='yummy.goods', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Название рецепта слишком короткое'), django.core.validators.MaxLengthValidator(limit_value=100, message='Название рецепта слишком длинное')], verbose_name='Название'),
        ),
    ]
