# Generated by Django 4.0.6 on 2023-05-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0017_alter_comments_comment_alter_goods_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
