# Generated by Django 4.0.6 on 2023-05-28 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0019_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=1000, message='Количество слишком большое'), django.core.validators.MinValueValidator(limit_value=1, message='Количество слишком маленькое')], verbose_name='Количество'),
        ),
    ]
