# Generated by Django 4.0.6 on 2023-05-28 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0020_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(max_length=4000, verbose_name='Приготовление'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/', validators=[django.core.validators.validate_image_file_extension], verbose_name='Фотография готового блюда'),
        ),
    ]
