# Generated by Django 4.0.6 on 2023-05-28 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0021_alter_recipe_description_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=1000, message='Количество слишком большое'), django.core.validators.MinValueValidator(limit_value=0.01, message='Количество слишком маленькое')], verbose_name='Количество'),
        ),
    ]
