# Generated by Django 4.0.6 on 2023-05-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='users/user.svg', upload_to='users/', verbose_name='Фотография профиля'),
        ),
    ]
