# Generated by Django 4.0.6 on 2023-05-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('user__username',), 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
